[toolchain]
anchor_version = "0.31.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
aegis_vault = "71Wb7tohP36AHMxCoBaSL2osriCnNuxgdRNLyM9FZRu8"

[programs.localnet]
aegis_vault = "71Wb7tohP36AHMxCoBaSL2osriCnNuxgdRNLyM9FZRu8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
